on:
    push:
        branches:
        - master
        - 201904
    pull_request:
        branches:
        - master
        - 201904
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: crazy-max/ghaction-docker-buildx@v1
          with:
              version: latest
        - uses: actions/checkout@v2
        - run: git submodule update --init --recursive
        - run: make
