on:
    pull_request:
        branches:
        - master
        - 201811
        - 201904
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: crazy-max/ghaction-docker-buildx@v1
          with:
              version: latest
        - uses: actions/checkout@v2
        - run: git submodule update --init --recursive
        - run: make
        - run: make docker-run-image
          env:
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
        - run: make docker-debug-image
          env:
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
              DOCKER_DEBUG_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic-debug
        - run: make
        - run: make docker-run-image
          env:
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
        - run: make docker-debug-image
          env:
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
              DOCKER_DEBUG_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic-debug
