on:
    push:
        branches:
        - master
        - 201811
        - 201904
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: git submodule update --init --recursive
        - run: |
            import os
            ref = os.environ['GITHUB_REF']
            branch = ref[11:]
            print("::set-env name=DOCKER_IMAGE_TAG::{}".format('latest' if branch == 'master' else branch))
          shell: python
        - run: make
          env:
              DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
        - run: make docker-run-image
          env:
              DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
        - run: make docker-debug-image
          env:
              DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
              DOCKER_RUN_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic
              DOCKER_DEBUG_IMAGE: ${{ secrets.DOCKER_USERNAME }}/usonic-debug
        - name: Publish Docker image
          uses: ./.github/actions/publish-docker-image
          with:
              name: ${{ secrets.DOCKER_USERNAME }}/usonic
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              tags: ${{ env.DOCKER_IMAGE_TAG }}
        - name: Publish Docker image for debugging
          uses: ./.github/actions/publish-docker-image
          with:
              name: ${{ secrets.DOCKER_USERNAME }}/usonic-debug
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              tags: ${{ env.DOCKER_IMAGE_TAG }}
